### ISSUE TITLE
Track both fc & cc + add timestamps to last seen online

### ISSUE THREAD

**Issue by YvesW** [Phobos97/clan-activity-tracker#2]
If possible, it'd be awesome if we could track both the FC and CC, since we use both of them for the clan I'm in. Additionally, it'd be cool if timestamps could be added to the last seen online part of the .csv file. That'd allow me to copy it after a clan event to see who was online during the event. I suppose for members still online, it could add a "Still online" status instead of a timestamp?

**Comment by Phobos97** [comment]
I have added an option to track Both :) and have also added the exact timestamp for the last seen. The timestamps are only updated when they send a message or when you join the clan/fc. So you should probably leave and re-enter the clan chat during the event to get everyone's latest timestamp. GL!

I have just pushed this update to the Plugin Hub but it might be a day or so before the changes are added in the client.

**Comment by YvesW** [comment]
Ah, that's awesome! Thank you very much! :)
